### ISSUE TITLE
Tools not receiving arguments

### ISSUE THREAD

**Issue by Rollingpig** [kd-research/Techies#41]
## How to reproduce

Set a `techies/fixtures/soundcrew` folder with:

crews.yml
```yaml
_crew_common: &crew_common
  cache: false
  max_iter: 100
  memory: false

soundcrew:
  <<: *crew_common
  agents:
    - sound_engineer
  tasks:
    - find_sound_task
  input_args:
    - user_instruction
```

agents.yml
```yaml
_common: &common_attributes
  verbose: true
  allow_delegation: true

_no_deleg: &common_attributes_no_deleg
  <<: *common_attributes
  allow_delegation: false


sound_engineer:
  <<: *common_attributes_no_deleg
  goal: >
    Search for, choose and download sounds as requested by your coworkers.
    Sound files must be saved in the current working directory. Do not create a separate directory to store sound files.
    Suffix of sound files will be attached automatically, use list_files to identify the correct suffix.
    Create a file, listing the name location and description of each sound you download.
    # User instructions:
    {user_instruction}
  backstory: >
    You should act as the experienced sound designer.
    Your sounds will be used to create a game.
  tools:
    - list_files
    - write_file
    - search_sound
    - save_sound
```

tasks.yml
```yaml
_task_common: &task_common
  human_input: false
  async_execution: false

find_sound_task:
  <<: *task_common
  agent: sound_engineer
  description: >
    Use tools to find sounds that are suitable for the description.
  expected_output: >
    After the task is completed, the agent should have 3 sounds that are suitable for the description.
# vim: set foldmethod=indent foldlevel=0:
```

Run
```bash
techies --allow-load-scripts run soundcrew "bird singing"
```

## Terminal outputs
```text
# Agent: sound_engineer
## Thought: Thought: It looks like the same error keeps occurring with the search_sound tool. I should attempt a broader query in case the issue is with the search term.
## Using tool: search_sound
## Tool Input:
"{\"query\": \"bird\", \"min_duration\": 3, \"max_duration\": 20, \"max_results\": 10}"
## Tool Output:

I encountered an error while trying to use the tool. This was the error: can only concatenate str (not "NoneType") to str.
 Tool search_sound accepts these inputs: Tool Name: search_sound
Tool Arguments: {'query': {'description': 'Search query for the sound.', 'type': 'str'}, 'min_duration': {'description': 'Minimum duration of the sound in seconds.', 'type': 'int'}, 'max_duration': {'description': 'Maximum duration of the sound in seconds.', 'type': 'int'}, 'max_results': {'description': 'Maximum number of search results to return.', 'type': 'int'}}
Tool Description: Search for sounds using the FreeSound API..
```
